language: java
jdk:
  - oraclejdk8
before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
  - tar zxvf apache-maven-3.5.0-bin.tar.gz
  - chmod +x apache-maven-3.5.0/bin/mvn
  - export M2_HOME=$PWD/apache-maven-3.5.0
  - export PATH=$PWD/apache-maven-3.5.0/bin:${PATH}
  - hash -r
before_script:
  - export M2_HOME=$PWD/apache-maven-3.5.0
  - export PATH=$PWD/apache-maven-3.5.0/bin:${PATH}
  - hash -r
script: mvn verify -Dgpg.skip=true